# version: '1'
services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "${PGADMIN_PORT:-5050}:80" #prend dans .env sinon 5050
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin:/var/lib/pgadmin
    restart: always

volumes:
  pgadmin:
